name: canverro_gallery_task
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  freezed_annotation: ^2.4.1
  get_it: ^7.6.6
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.0.3

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_serializable: ^6.4.1
  mocktail: ^1.0.0
  retrofit_generator: 8.1.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  # assets:
  #   - .env.dev
  #   - .env.production
  #   - .env.staging
